56 lombok
sosyal-app/backend pull request #60
Opened 2023-08-28 21:34 UTC by gozdekalman

2023-08-29 05:22 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:23 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:25 UTC, Mert18 requested changes
Account class'ında bazı değişmemesi gereken değerler değişmiş.  birkaç log satırı var onlar bu task'in görevi değil.

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/model/Account.java
> +        return false;
Bu değeri neden değiştirdik?

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/service/AccountService.java
> +    private final static Logger logger = LoggerFactory.getLogger(AccountService.class);
Log task'inde yapılan ya da yapılması gereken bir şey. Silelim

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/service/AccountService.java
> +            logger.info("created account");
Log task'inde yapılan ya da yapılması gereken bir şey. Silelim

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/service/AccountService.java
> +                logger.error("email or password is wrong!!");
Log task'inde yapılan ya da yapılması gereken bir şey. Silelim

2023-08-29 05:25 UTC, Mert18 commented on src/main/java/com/developers/sosyalapp/service/AccountService.java
> +            logger.info("login successful");
Log task'inde yapılan ya da yapılması gereken bir şey. Silelim

2023-08-29 06:15 UTC, gozdekalman commented
sds

2023-08-30 12:52 UTC, gozdekalman commented
problem fix with 0558083e4e324ab9da62f1a71a2e07622ce33e4e

2023-08-30 12:53 UTC, Mert18 approved these changes

2023-08-30 12:54 UTC, merged